pipeline {
  agent any

  options {
    ansiColor('xterm')
  }

  stages {
    stage ('Run tests and code analysis') {
        steps {
            withMaven(maven: "MAVEN_381", mavenSettingsConfig: 'maven-settings') {
                bat "mvn clean test"
             }
        }
    }
  }
}

